---
- name: Install docker-ce via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker -y"

- name: Enable Docker CE service at startup
  systemd: 
    name: docker
    state: started
    enabled: yes

- name: Add users to "docker" group
  shell: sudo usermod -a -G docker ec2-user

- name: Reload services 
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
